services:
  rpi-streaming-sensor-base-bookworm:
    build:
      context: .
      dockerfile: Dockerfile.bookworm
      args:
        - COMMIT_HASH=${COMMIT_HASH}
    image: registry.hackeneering.com/hackeneering/rpi-streaming-sensor-base:bookworm-arm64-${COMMIT_HASH}
    platform: linux/arm64
